name: Build and Package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.JAVA_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Publish package
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          JAVA_TOKEN: ${{ secrets.JAVA_TOKEN }}